spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/apidatabaseteste?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: off